### PR TITLE
Hello Rails back end milestone 1 : Api setup

### PR DESCRIPTION
**Pull request by Nemwel-Boniface**
## Hello reviewer(s) :wave: 

In this milestone, I was able to set up the API application for the Hello Rails back end. The specific tasks achieved include: 

- [x] Setup project Workflows
- [x] Setup project linters
- [x] Created the API endpoints for my project and tested it
- [x] Updated the project documentation
- [x] Checked and fixed all found Robocop offenses

**This is the link to the front end:** [here](https://github.com/Nemwel-Boniface/hello-react-front-end/pull/1)

Thank you for taking the time to review my project :pray:

### CODE REVIEW

**Comment by thecodechaser** [comment]
@Nemwel-Boniface Please check my message on slack

**Review by thecodechaser — APPROVED** [review]
## STATUS: APPROVED 🟢

## Hi @Nemwel-Boniface👋, 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

image

## To Highlight 🎉
- No linter errors. :heavy_check_mark:
- Gitflow is followed. :heavy_check_mark:
- Professional README file. :heavy_check_mark:
- PR has a good title and summary. ✔️



Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Comment by Nemwel-Boniface** [comment]
Asante sana @thecodechaser  :pray:

**Comment by thecodechaser** [comment]
@Nemwel-Boniface Karibu 😄

**Pull request merged**
